# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('Compliments', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gratitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('give_gratitude', models.BooleanField()),
                ('remove_gratitude', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('liked', models.BooleanField()),
                ('unliked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('message_body', models.CharField(max_length=200)),
                ('moderator_approval_count', models.IntegerField(default=0)),
                ('verified_by_moderators', models.BooleanField(default=True)),
                ('last_like_activity_id', models.IntegerField(default=-1, null=True)),
                ('last_like_count', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('msg_count', models.IntegerField(default=0)),
                ('last_msg_activity_id', models.IntegerField(default=-1, null=True)),
                ('gratitude_count', models.IntegerField(default=0)),
                ('last_gratiude_activity_id', models.IntegerField(default=-1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Compliments.Teachers'),
        ),
        migrations.AddField(
            model_name='likes',
            name='message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Compliments.Messages'),
        ),
        migrations.AddField(
            model_name='gratitude',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratitude', to='Compliments.Teachers'),
        ),
    ]
