# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compliments', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_abbr', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='teachers',
            name='abbr',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='teachers',
            name='name',
            field=models.CharField(default=('RKD', 'RKD'), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers',
            name='dept',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='Compliments.Departments'),
            preserve_default=False,
        ),
    ]
