# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compliments', '0002_auto_20170820_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='last_gratiude_activity_id',
            new_name='last_gratitude_activity_id',
        ),
    ]
