# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compliments', '0007_auto_20170826_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='verified_by_moderators',
            field=models.BooleanField(default=False),
        ),
    ]
