# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compliments', '0008_auto_20170827_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='deleted_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
