# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 15:24
from __future__ import unicode_literals

import Authenticate.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Compliments', '0004_auto_20170822_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbableUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('signed_up', models.BooleanField(default=False)),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='probable_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('year_of_study', models.IntegerField(validators=[Authenticate.models.RegisteredUsers.validity_year])),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_users', to='Compliments.Departments')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
