# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 19:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Compliments', '0004_auto_20170822_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('upvoted', models.BooleanField()),
                ('downvoted', models.BooleanField()),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_activity', to='Compliments.Messages')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('moderator_permission', 'eligible to be a moderator'),),
            },
        ),
    ]
