# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderatoractivity',
            options={},
        ),
    ]
